### PR TITLE
HCAP-1421: Limited allocation to 100k to prevent errors

### PR DESCRIPTION
**Pull request by rhattie-ey**
Adds validation to allocation form to prevent server errors ([HCAP-1421](https://eydscanada.atlassian.net/browse/HCAP-1421)).

### CODE REVIEW

**Review by fw-noel — APPROVED** [review]
May want to do a BE validation check too

**Review by mmumby — COMMENTED** [review]
Looks great, could you also add it to the server validations?

**Review by mmumby — APPROVED** [review]
🎉

**Review by vanics — APPROVED** [review]
Looks good!

**Pull request merged**
