### PR TITLE
Lock Versions + Rerun npm i

### PR DESCRIPTION
**Pull request by arranfw**
- Locks package versions
- Updates package-lock files (they were out of step)

### CODE REVIEW

**Review by dbayly-freshworks — APPROVED** [review]
I get locking down the packages in package.json, but why lockdown packages inside the package-lock?

**Comment by arranfw** [comment]
> I get locking down the packages in package.json, but why lockdown packages inside the package-lock?

That's the auto-output from npm, I think I missed it when finishing up the last prettier/eslint PR

**Comment by dbayly-freshworks** [comment]
> > I get locking down the packages in package.json, but why lockdown packages inside the package-lock?
> 
> That's the auto-output from npm, I think I missed it when finishing up the last prettier/eslint PR, if you have a moment could you pull this branch and verify you don't get a diff after running `npm run update-all`?

I just did this and there was no diff. 👍

**Review by fwpushan — APPROVED** [review]
👍

**Pull request merged**
