### PR TITLE
Hcap 773 intent to rehire

### PR DESCRIPTION
**Pull request by dbayly-freshworks**
Screen Shot 2021-07-26 at 11 32 13 AM

Added intent to rehire radio box group to Archive Participant workflow.

### CODE REVIEW

**Comment by arranfw** [comment]
In my local testing I didn't see the new column added to the CSV export, can you verify?

**Comment by dbayly-freshworks** [comment]
> In my local testing I didn't see the new column added to the CSV export, can you verify?

I ran into the same issue. It's why I switched this to a WIP.

**Comment by arranfw** [comment]
> > In my local testing I didn't see the new column added to the CSV export, can you verify?
> 
> I ran into the same issue. It's why I switched this to a WIP.

Ahh sorry I didn't see that!

**Review by arranfw — APPROVED** [review]
Looks good!

**Review by fwpushan — APPROVED** [review]

**Pull request merged**
